name: Build & Deploy (Cloudflare Pages)

on:
  push:
    branches: [ "**" ]   # todas las ramas (incluida main)
  pull_request:

concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Cache pub
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web (release)
        run: flutter build web --release

      # Preview: PRs y pushes a ramas ≠ main
      - name: Deploy Preview
        if: github.event_name == 'pull_request' || github.ref != 'refs/heads/main'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: >
            pages deploy build/web
            --project-name=narra
            --branch=${{ github.head_ref || github.ref_name }}
            --commit-hash=${{ github.sha }}
            --commit-message="CI preview ${{ github.sha }}"
            --commit-dirty=true
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      # Production: solo push a main (sin --production)
      - name: Deploy Production
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: >
            pages deploy build/web
            --project-name=narra
            --branch=main
            --commit-hash=${{ github.sha }}
            --commit-message="${{ github.event.head_commit.message }}"
            --commit-dirty=true
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
